// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Post: typeof import('./src/components/Post.vue')['default']
    Posts: typeof import('./src/components/Posts.vue')['default']
  }
}
